services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./Database/mongo-init:/docker-entrypoint-initdb.d

  database_adapter:
    build:
      context: ./Database
      dockerfile: Dockerfile
    depends_on:
    #Later add the dependency to the RabbitMQ
      - db
    
  restapi:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:${MONGO_INITDB_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
    depends_on:
      - db 
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Frontend/Carbox  
      dockerfile: Dockerfile  
    ports:
      - "80:5173" 
    depends_on:
      - restapi 
    environment:
      API_URL: http://restapi:8080