services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./Database/mongo-init:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Cache/redis-data:/data
      - ./Cache/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_ARGS="--requirepass ${REDIS_PASSWORD} --save ${REDIS_SNAPSHOT_PERIOD} ${REDIS_SNAPSHOT_MIN_CHANGE} --appendonly yes"

  restapi:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:${MONGO_INITDB_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin
      SPRING_REDIS_HOST: redis
      SPRING_APPLICATION_JSON: '{
          "spring.data.redis.host": "${REDIS_HOST}",
          "spring.data.redis.port": "${REDIS_PORT}",
          "spring.data.redis.password": "${REDIS_PASSWORD}"
        }'
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Frontend/Carbox
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    depends_on:
      - restapi
    environment:
      API_URL: http://restapi:8080
