services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: carbox
      MONGO_INITDB_ROOT_USERNAME: carbox
      MONGO_INITDB_ROOT_PASSWORD: mySecretPassword
    volumes:
      - ./Database/mongo-init:/docker-entrypoint-initdb.d

  restapi:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile  # Dockerfile for the Spring Boot backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://carbox:mySecretPassword@db:27017/carbox?authSource=admin
    depends_on:
      - db  # Ensure db starts before restapi
    ports:
      - "8080:8080"  # Expose REST API on port 8080

  frontend:
    build:
      context: ./Frontend/Carbox  # Path to your frontend source code
      dockerfile: Dockerfile  # Dockerfile for the frontend
    ports:
      - "80:5173"  # Expose the frontend on port 80 (default HTTP port)
    depends_on:
      - restapi  # Ensure restapi starts before frontend
    environment:
      API_URL: http://restapi:8080  