export default interface Vehicle {
    ecuId: string,
    lastRevision: string,
    brand: string,
    model: string,
    licensePlate: string,
    year: number,
    tires: string,
    motor: string,
    tank: string,
    maxSpeed: number,
    horsepower: number,
    autonomy: number,
    carStatus: boolean,
    location: string,
    name?: string,
}